#
# CONFIGURACIONES DE TOMCAT EMBED
#
server:
    port: 8080
    contextPath: /ch01

#
# CONFIGURACIONES DE SPRING
#
spring:    
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

